node {
    checkout scm
    docker.image('maven:3.5.4-alpine').inside('-v /root/.m2:/root/.m2') {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        stage('Test') {
            sh 'mvn test'
        }
        stage('Deploy') {
            sh './jenkins/scripts/deliver.sh'
            withCredentials([
                    sshUserPrivateKey(credentialsId: 'root', keyFileVariable: 'secret')
                ]) {
                    rsync -avz -e "'${secret}'" target/my-app-1.0-SNAPSHOT.jar ubuntu@$tkjpedia:/root/workspace/dicoding/
                }
        }
    }
}