node {
    checkout scm
    // docker.image('maven:3.5.4-alpine').inside('-v /root/.m2:/root/.m2') {
    //     stage('Build') {
    //         sh 'mvn -B -DskipTests clean package'
    //     }
    //     stage('Test') {
    //         sh 'mvn test'
    //     }
    //     stage('Deliver') {
    //         sh './jenkins/scripts/deliver.sh'
    //     }
    // }
    docker.image('ubuntu:latest').inside('-e TZ=Asia/Jakarta') {
        stage('Deploy') {
            sh "which ssh-agent || ( sudo apt-get update -y && sudo apt-get install openssh-client -y )"
            withCredentials([
                    sshUserPrivateKey(credentialsId: 'root', keyFileVariable: 'key')
                ]) {
                    sh "mkdir -p ~/.ssh"
                    sh "[[ -f /.dockerenv ]] && echo -e 'Host *\n\tStrictHostKeyChecking no\n\n' > ~/.ssh/config"
                    sh "ssh-add <(echo '$key')"
                    sh "ssh -o StrictHostKeyChecking=no $ubuntu@$key 'ls -al'"
                }
        } 
    }
}